name: 'Unity Linter'
description: 'Greet someone and record the time'
inputs:
    version:
        description: 'Unity version to use'
        required: true
    platform:
        description: 'Unity platform to use'
        required: true
    who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'
runs:
    using: 'composite'
    steps:
      - run: sed -i 's/UNITY_VERSION/${{ inputs.version }}/g' 'Dockerfile'
        shell: bash
      - run: sed -i 's/UNITY_PLATFORM/${{ inputs.platform }}/g' 'Dockerfile'
        shell: bash
      - run: docker build - --tag unitylinter:1.0 < Dockerfile
        shell: bash
      - run: docker run --rf unitylinter:1.0
        shell: bash