name: 'Unity Linter'
description: 'Greet someone and record the time'
inputs:
    version:
        description: 'Unity version to use'
        required: true
    platform:
        description: 'Unity platform to use'
        required: true
    who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'
runs:
    using: 'composite'
    steps:
      - run: docker build ${{ github.action_path }} --build-arg unity_version=${{ inputs.version }} --build-arg unity_platform=${{ inputs.platform }} --tag unitylinter:1.0
        shell: bash
      - run: docker run --rf unitylinter:1.0
        shell: bash