name: 'Unity Linter'
description: 'Greet someone and record the time'
inputs:
  version:
    description: 'Unity version to use'
    required: true
  platform:
    description: 'Unity platform to use'
    required: true
  username:
    description: 'Unity account username'
    required: true
  password:
    description: 'Unity account password'
    required: true
  projectPath:
    description: 'Path to unity project'
    required: true
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  testResult:
    description: "Test result of unity"
    value: ${{ steps.unity-run.outputs.testResultFile }}

runs:
  using: 'composite'
  steps:
    - run: echo ${{ inputs.version }}
      shell: bash
    - run: echo ${{ inputs.platform }}
      shell: bash
    - run: echo ${{ inputs.projectPath }}
      shell: bash
    - run: docker build ${{ github.action_path }} --build-arg unity_version=${{ inputs.version }} --build-arg unity_platform=${{ inputs.platform }} --tag unitylinter:1.0
      shell: bash
    - id: unity-run
      run: docker run -t --rm unitylinter:1.0 -v "${{ inputs.projectPath }}":"/workspace" -e UNITY_USERNAME=${{ inputs.username }} -e UNITY_PASSWORD=${{ inputs.password }}
      shell: bash